import { Schema, SchemaNode } from "../core/schema.js";
import { Snapshot } from "../core/storage.js";

/**
 * Generate a TypeScript interface name from an endpoint URL
 */
function endpointToTypeName(endpoint: string): string {
  const url = endpoint.replace(/^https?:\/\/[^/]+/, ""); // strip origin
  const parts = url
    .split("/")
    .filter(Boolean)
    .map((p) =>
      p
        .replace(/[^a-zA-Z0-9]/g, "_")
        .replace(/^_+|_+$/g, "")
        .replace(/_+/g, "_")
    )
    .filter(Boolean);

  if (parts.length === 0) return "ApiResponse";

  const name = parts
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase())
    .join("_");

  return `${name}Response`;
}

/**
 * Convert a SchemaNode to a TypeScript type string
 */
function nodeToTS(node: SchemaNode, indent: number = 0): string {
  const pad = "  ".repeat(indent);

  let base: string;

  if (node.enum && node.enum.length > 0) {
    base = node.enum.map((v) => JSON.stringify(v)).join(" | ");
    if (node.sensitive) base += ` /* sensitive */`;
  } else {
    switch (node.type) {
      case "string":
        base = "string";
        if (node.pattern) base += ` /* pattern: ${node.pattern} */`;
        if (node.sensitive) base += ` /* sensitive */`;
        break;
      case "number":
        base = "number";
        if (node.sensitive) base += ` /* sensitive */`;
        break;
      case "boolean":
        base = "boolean";
        if (node.sensitive) base += ` /* sensitive */`;
        break;
      case "null":
        base = "null";
        break;
      case "unknown":
        base = "unknown";
        break;
      case "array":
        if (node.items) {
          const itemType = nodeToTS(node.items, indent);
          base = node.items.type === "object" ? `Array<${itemType}>` : `${itemType}[]`;
        } else {
          base = "unknown[]";
        }
        break;
      case "object":
        if (!node.children || Object.keys(node.children).length === 0) {
          base = "Record<string, unknown>";
        } else {
          const childLines = Object.entries(node.children).map(([key, child]) => {
            const optional = child.optional ? "?" : "";
            const type = nodeToTS(child, indent + 1);
            return `${"  ".repeat(indent + 1)}${key}${optional}: ${type};`;
          });
          base = `{\n${childLines.join("\n")}\n${pad}}`;
        }
        break;
      default:
        base = "unknown";
    }
  }

  if (node.nullable) {
    base = `(${base}) | null`;
  }

  return base;
}

/**
 * Generate a TypeScript interface from a Schema
 */
export function generateInterface(name: string, schema: Schema): string {
  if (schema._root) {
    return `export type ${name} = ${nodeToTS(schema._root)};`;
  }

  const lines: string[] = [];
  lines.push(`export interface ${name} {`);

  for (const [key, node] of Object.entries(schema)) {
    const optional = node.optional ? "?" : "";
    const type = nodeToTS(node, 1);
    lines.push(`  ${key}${optional}: ${type};`);
  }

  lines.push(`}`);
  return lines.join("\n");
}

/**
 * Generate TypeScript types from all snapshots
 */
export function generateTypesFromSnapshots(snapshots: Snapshot[]): string {
  const header = [
    `// Generated by apidrift`,
    `// ${new Date().toISOString()}`,
    `// Do not edit manually — run \`apidrift types\` to regenerate`,
    ``,
  ].join("\n");

  const interfaces = snapshots.map((snap) => {
    const name = endpointToTypeName(snap.endpoint);
    return generateInterface(name, snap.schema);
  });

  return header + interfaces.join("\n\n") + "\n";
}
